graph TD
  subgraph Input data
    A[Extant genomes]
    B[Species tree]
    C[Gene phylogenies]
    D[Extant gene orders]
  end
  subgraph AGORA
    E[Ancestral gene lists]
    F[Pairwise comparisons]
    G[Ancestral gene order]
    H[Block assembly]
  end
  subgraph Output
    I[Contiguous Ancestral Regions]
  end
  A -.- B & C & D
  C --> E
  B --> H & F
  D --> F & H
  E --> F --> G --> H --> I
